declare const _default: {
    Band: import("prop-types").Requireable<import("prop-types").InferProps<{
        _id: import("prop-types").Validator<string>;
        cityName: import("prop-types").Requireable<string>;
        cityPlaceID: import("prop-types").Requireable<string>;
        dateCreated: import("prop-types").Validator<string | Date>;
        dateModified: import("prop-types").Validator<string | Date>;
        description: import("prop-types").Requireable<string>;
        email: import("prop-types").Requireable<string>;
        facebook: import("prop-types").Requireable<string>;
        facebookPageId: import("prop-types").Requireable<string>;
        facebookPageName: import("prop-types").Requireable<string>;
        facebookPageToken: import("prop-types").Requireable<string>;
        google: import("prop-types").Requireable<string>;
        icon: import("prop-types").Requireable<string>;
        metadata: import("prop-types").Requireable<string>;
        name: import("prop-types").Validator<string>;
        owners: import("prop-types").Requireable<string[]>;
        photos: import("prop-types").Requireable<string[]>;
        twitter: import("prop-types").Requireable<string>;
        website: import("prop-types").Requireable<string>;
    }>>;
    Conversation: import("prop-types").Requireable<import("prop-types").InferProps<{
        _id: import("prop-types").Validator<string>;
        dateCreated: import("prop-types").Validator<string | Date>;
        dateModified: import("prop-types").Validator<string | Date>;
        events: import("prop-types").Requireable<import("prop-types").InferProps<{
            dateTimePosted: import("prop-types").Validator<string>;
            message: import("prop-types").Validator<string>;
            user: import("prop-types").Validator<string>;
        }>[]>;
        users: import("prop-types").Requireable<string[]>;
    }>>;
    ErrorReport: import("prop-types").Requireable<import("prop-types").InferProps<{
        _id: import("prop-types").Validator<string>;
        columnNumber: import("prop-types").Requireable<number>;
        dateCreated: import("prop-types").Validator<string | Date>;
        dateModified: import("prop-types").Validator<string | Date>;
        fileName: import("prop-types").Requireable<string>;
        lineNumber: import("prop-types").Requireable<number>;
        message: import("prop-types").Validator<string>;
        name: import("prop-types").Validator<string>;
        stack: import("prop-types").Validator<string>;
        userId: import("prop-types").Validator<string>;
        version: import("prop-types").Validator<string>;
    }>>;
    FacebookAccount: import("prop-types").Requireable<import("prop-types").InferProps<{
        _id: import("prop-types").Validator<string>;
        accountId: import("prop-types").Validator<string>;
        dateCreated: import("prop-types").Validator<string | Date>;
        dateModified: import("prop-types").Validator<string | Date>;
        profile: import("prop-types").Requireable<any>;
        userAccessToken: import("prop-types").Requireable<string>;
        userId: import("prop-types").Validator<string>;
        userRefreshToken: import("prop-types").Requireable<string>;
    }>>;
    Gig: import("prop-types").Requireable<import("prop-types").InferProps<{
        _id: import("prop-types").Validator<string>;
        bandOwnerAccepted: import("prop-types").Requireable<string>;
        bands: import("prop-types").Validator<string[]>;
        dateCreated: import("prop-types").Validator<string | Date>;
        dateModified: import("prop-types").Validator<string | Date>;
        location: import("prop-types").Validator<string>;
        owners: import("prop-types").Requireable<string[]>;
        startTime: import("prop-types").Validator<string | Date>;
        stopTime: import("prop-types").Validator<string | Date>;
        toBeAnnounced: import("prop-types").Requireable<boolean>;
        venue: import("prop-types").Validator<string>;
        venueOwnerAccepted: import("prop-types").Requireable<string>;
    }>>;
    Location: import("prop-types").Requireable<import("prop-types").InferProps<{
        _id: import("prop-types").Validator<string>;
        address: import("prop-types").Validator<string>;
        dateCreated: import("prop-types").Validator<string | Date>;
        dateModified: import("prop-types").Validator<string | Date>;
        placeId: import("prop-types").Validator<string>;
        point: import("prop-types").Validator<number[]>;
        type: import("prop-types").Validator<string>;
        utcOffset: import("prop-types").Validator<number>;
    }>>;
    Notification: import("prop-types").Requireable<import("prop-types").InferProps<{
        _id: import("prop-types").Validator<string>;
        actions: import("prop-types").Requireable<import("prop-types").InferProps<{
            label: import("prop-types").Validator<string>;
            link: import("prop-types").Requireable<string>;
            request: import("prop-types").Requireable<string>;
        }>[]>;
        dateCreated: import("prop-types").Validator<string | Date>;
        dateModified: import("prop-types").Validator<string | Date>;
        label: import("prop-types").Validator<string>;
        message: import("prop-types").Validator<string>;
        seenByUser: import("prop-types").Requireable<boolean>;
        userId: import("prop-types").Validator<string>;
    }>>;
    Page: import("prop-types").Requireable<import("prop-types").InferProps<{
        _id: import("prop-types").Validator<string>;
        blog: import("prop-types").Requireable<boolean>;
        data: import("prop-types").Requireable<string>;
        dateCreated: import("prop-types").Validator<string | Date>;
        dateModified: import("prop-types").Validator<string | Date>;
        doc: import("prop-types").Requireable<boolean>;
        hide: import("prop-types").Requireable<boolean>;
        link: import("prop-types").Requireable<string>;
        metadata: import("prop-types").Requireable<string>;
        revisions: import("prop-types").Requireable<number>;
        title: import("prop-types").Requireable<string>;
        visits: import("prop-types").Requireable<number>;
    }>>;
    Post: import("prop-types").Requireable<import("prop-types").InferProps<{
        _id: import("prop-types").Validator<string>;
        accountId: import("prop-types").Validator<string>;
        coordinates: import("prop-types").Requireable<number[]>;
        dateCreated: import("prop-types").Validator<string | Date>;
        dateModified: import("prop-types").Validator<string | Date>;
        done: import("prop-types").Validator<boolean>;
        error: import("prop-types").Requireable<any>;
        network: import("prop-types").Validator<string>;
        pageId: import("prop-types").Validator<string>;
        postDate: import("prop-types").Validator<string | Date>;
        postText: import("prop-types").Validator<string>;
        userId: import("prop-types").Validator<string>;
    }>>;
    TwitterAccount: import("prop-types").Requireable<import("prop-types").InferProps<{
        _id: import("prop-types").Validator<string>;
        accessToken: import("prop-types").Requireable<string>;
        accountId: import("prop-types").Validator<string>;
        dateCreated: import("prop-types").Validator<string | Date>;
        dateModified: import("prop-types").Validator<string | Date>;
        profile: import("prop-types").Requireable<any>;
        tokenSecret: import("prop-types").Requireable<string>;
        userId: import("prop-types").Validator<string>;
    }>>;
    Upload: import("prop-types").Requireable<import("prop-types").InferProps<{
        _id: import("prop-types").Validator<string>;
        dateCreated: import("prop-types").Validator<string | Date>;
        dateModified: import("prop-types").Validator<string | Date>;
        description: import("prop-types").Requireable<string>;
        fileData: import("prop-types").Validator<string>;
        fileName: import("prop-types").Validator<string>;
        owners: import("prop-types").Validator<string[]>;
        title: import("prop-types").Validator<string>;
    }>>;
    User: import("prop-types").Requireable<import("prop-types").InferProps<{
        _id: import("prop-types").Validator<string>;
        active: import("prop-types").Requireable<boolean>;
        admin: import("prop-types").Requireable<boolean>;
        attempts: import("prop-types").Requireable<number>;
        bandManager: import("prop-types").Requireable<boolean>;
        betaFeatureUser: import("prop-types").Requireable<boolean>;
        birthday: import("prop-types").Validator<string | Date>;
        country: import("prop-types").Validator<string>;
        dateCreated: import("prop-types").Validator<string | Date>;
        dateModified: import("prop-types").Validator<string | Date>;
        description: import("prop-types").Requireable<string>;
        email: import("prop-types").Requireable<string>;
        emailVerified: import("prop-types").Requireable<boolean>;
        facebook: import("prop-types").Requireable<string>;
        firstName: import("prop-types").Validator<string>;
        icon: import("prop-types").Requireable<string>;
        lastLogin: import("prop-types").Validator<string | Date>;
        lastLoginIP: import("prop-types").Validator<string>;
        lastName: import("prop-types").Validator<string>;
        middleName: import("prop-types").Requireable<string>;
        payment: import("prop-types").Requireable<string>;
        paypal: import("prop-types").Requireable<string>;
        sendAnonymousReports: import("prop-types").Requireable<boolean>;
        sendEmails: import("prop-types").Requireable<boolean>;
        sendErrorReports: import("prop-types").Requireable<boolean>;
        sendPromotions: import("prop-types").Requireable<boolean>;
        twitter: import("prop-types").Requireable<string>;
        useCookies: import("prop-types").Requireable<boolean>;
        venueManager: import("prop-types").Requireable<boolean>;
    }>>;
    Venue: import("prop-types").Requireable<import("prop-types").InferProps<{
        _id: import("prop-types").Validator<string>;
        dateCreated: import("prop-types").Validator<string | Date>;
        dateModified: import("prop-types").Validator<string | Date>;
        description: import("prop-types").Validator<string>;
        email: import("prop-types").Requireable<string>;
        facebook: import("prop-types").Requireable<string>;
        facebookPageId: import("prop-types").Requireable<string>;
        facebookPageName: import("prop-types").Requireable<string>;
        facebookPageToken: import("prop-types").Requireable<string>;
        google: import("prop-types").Requireable<string>;
        icon: import("prop-types").Requireable<string>;
        location: import("prop-types").Validator<string>;
        metaData: import("prop-types").Requireable<string>;
        name: import("prop-types").Validator<string>;
        openCloseTimes: import("prop-types").Requireable<import("prop-types").InferProps<{
            closingTime: import("prop-types").Requireable<string>;
            open: import("prop-types").Requireable<boolean>;
            openingTime: import("prop-types").Requireable<string>;
        }>[]>;
        owners: import("prop-types").Requireable<string[]>;
        phone: import("prop-types").Requireable<string>;
        photos: import("prop-types").Requireable<string[]>;
        twitter: import("prop-types").Requireable<string>;
        website: import("prop-types").Requireable<string>;
    }>>;
};
export default _default;
