import * as PropTypes from "prop-types";
declare const _default: PropTypes.Requireable<PropTypes.InferProps<{
    _id: PropTypes.Validator<string>;
    dateCreated: PropTypes.Validator<string | Date>;
    dateModified: PropTypes.Validator<string | Date>;
    icon: PropTypes.Requireable<string>;
    email: PropTypes.Requireable<string>;
    firstName: PropTypes.Validator<string>;
    middleName: PropTypes.Requireable<string>;
    lastName: PropTypes.Validator<string>;
    birthday: PropTypes.Validator<string | Date>;
    country: PropTypes.Validator<string>;
    bandManager: PropTypes.Requireable<boolean>;
    venueManager: PropTypes.Requireable<boolean>;
    betaFeatureUser: PropTypes.Requireable<boolean>;
    sendAnonymousReports: PropTypes.Requireable<boolean>;
    sendErrorReports: PropTypes.Requireable<boolean>;
    sendEmails: PropTypes.Requireable<boolean>;
    sendPromotions: PropTypes.Requireable<boolean>;
    useCookies: PropTypes.Requireable<boolean>;
    description: PropTypes.Requireable<string>;
    active: PropTypes.Requireable<boolean>;
    paypal: PropTypes.Requireable<string>;
    facebook: PropTypes.Requireable<string>;
    twitter: PropTypes.Requireable<string>;
    emailVerified: PropTypes.Requireable<boolean>;
    payment: PropTypes.Requireable<string>;
    admin: PropTypes.Requireable<boolean>;
    attempts: PropTypes.Requireable<number>;
    lastLogin: PropTypes.Validator<string | Date>;
    lastLoginIP: PropTypes.Validator<string>;
}>>;
export default _default;
