import * as PropTypes from "prop-types";
declare const _default: PropTypes.Requireable<PropTypes.InferProps<{
		_id: PropTypes.Validator<string>;
		active: PropTypes.Requireable<boolean>;
		admin: PropTypes.Requireable<boolean>;
		attempts: PropTypes.Requireable<number>;
		bandManager: PropTypes.Requireable<boolean>;
		betaFeatureUser: PropTypes.Requireable<boolean>;
		birthday: PropTypes.Validator<string | Date>;
		country: PropTypes.Validator<string>;
		dateCreated: PropTypes.Validator<string | Date>;
		dateModified: PropTypes.Validator<string | Date>;
		description: PropTypes.Requireable<string>;
		email: PropTypes.Requireable<string>;
		emailVerified: PropTypes.Requireable<boolean>;
		facebook: PropTypes.Requireable<string>;
		firstName: PropTypes.Validator<string>;
		icon: PropTypes.Requireable<string>;
		lastLogin: PropTypes.Validator<string | Date>;
		lastLoginIP: PropTypes.Validator<string>;
		lastName: PropTypes.Validator<string>;
		middleName: PropTypes.Requireable<string>;
		payment: PropTypes.Requireable<string>;
		paypal: PropTypes.Requireable<string>;
		sendAnonymousReports: PropTypes.Requireable<boolean>;
		sendEmails: PropTypes.Requireable<boolean>;
		sendErrorReports: PropTypes.Requireable<boolean>;
		sendPromotions: PropTypes.Requireable<boolean>;
		twitter: PropTypes.Requireable<string>;
		useCookies: PropTypes.Requireable<boolean>;
		venueManager: PropTypes.Requireable<boolean>;
}>>;
export default _default;
